env:
  global:
  - TZ=Europe/Helsinki
  - GH_REPO="github.com/alypo/alypo.github.io.git"
  - secure: "HKoYu6yzlvDZLfUWHG/XIrngAE7PIa9xg/BwunmPp1gnNwvJ78MXehSLVyUR/CZOBLjJlizc9BBCTN2gBDygICem9beeiBf0TLQ5Pwaxy8iph2+uKDd0yGSaL7mvCZfYR5qhoV5gAcF+ug0KJXsZRQKBmj9RSQeguyPEfK5OaK7oROLgMUb1AuSeYMkEL8cFGJdaIJ/Tqu1BrC8ksFmCSZ4VHhKO5z8jh1ifks/bv9CRwONie+Ylmqm9MwUJkpfnLg8rI1E+wa5bNWs1oHYhq59rD1sOe4kQL/vSmHzDMs235S8PWjgshkOmXZXoNFIPnLT2qHFWJ5s3yoFEH1v1/U6t9cK122RQ12G93ZFLdmU6eOoTrJLkxAYOqtX2IvwVd1bAO9TwnYHJGLyTUPl0r/6SPliTHyZuqvp7r5qwKKW1NXOPV8KdWFkRRFYfzGOo/OBRWF1XeJaZ3W65YSeugJVcwHoF15hMLIywmBfknSevLsbh0GL9BrsBWfY9ctWNk1N4MS6YiKzueHZGnqP2iqMIpq1wizU43gf0SeuLXYt8iTSatnKWo4xrekrACdBCu4jUxUbeiP1gjl6pDfktbY2bq0z8v4ybLBGW2MLk4AUmBPkNPhnEMYOOe9Aq6IRJewiyX+Z9JZ8FSntDjY/+Dbnhyfr39PBGdy17Ijb/Gbc="
language: node_js
node_js: node
branches:
  only:
  - master
before_install:
install: 
 - npm install hexo-generator-searchdb --save
 - npm install hexo-symbols-count-time --save
 - npm install hexo-generator-feed --save
 - npm install hexo-wordcount --save
 - npm install hexo-related-popular-posts --save
before_script:
 - sed -i "s/nadeshiko/${nadeshiko}/" _config.yml 
 - cd themes/next
 - git clone https://github.com/theme-next/theme-next-fancybox source/lib/fancybox
 - git clone https://github.com/theme-next/theme-next-fastclick source/lib/fastclick
 - git clone https://github.com/theme-next/theme-next-needmoreshare2 source/lib/needsharebutton
 - git clone https://github.com/theme-next/theme-next-pace source/lib/pace
 - git clone https://github.com/theme-next/theme-next-bookmark.git source/lib/bookmark 
 - cd ..
 - cd .. 
script:
 - hexo -version
 - hexo clean && hexo g
after_script:
 - hexo deploy --silent
